;;; custom.el --- Automatically generated by Emacs, keep in its own file. -*- lexical-binding: t; -*-
;;; Commentary:
;; This file is loaded by init.el, and is managed by Emacs' Customize interface.
;; You generally shouldn't edit this by hand unless you know what you're doing.

;;; Code:

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(claude-code inheritenv json-mode pyvenv typescript-mode web-mode))
 '(package-vc-selected-packages
   '((claude-code :url "https://github.com/stevemolitor/claude-code.el")))
 '(warning-suppress-log-types '((native-compiler))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;; custom.el ends here
